# Generated by Django 3.0.8 on 2020-07-03 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouruser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ouruser',
            table='django_basic_ouruser',
        ),
    ]
