# Generated by Django 3.0.2 on 2020-07-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ouruser', '0002_auto_20200703_2211'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouruser',
            name='usermail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
