# Generated by Django 3.0.2 on 2020-07-16 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ouruser', '0003_ouruser_usermail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ouruser',
            old_name='usermail',
            new_name='useremail',
        ),
    ]
